### ISSUE TITLE
Inconsistent license information

### ISSUE THREAD

**Issue by maxrjones** [GenericMappingTools/2021-unavco-course#16]
[LICENSE](https://github.com/GenericMappingTools/2021-unavco-course/blob/main/LICENSE) states LGPL v2.1 while [README.md](https://github.com/GenericMappingTools/2021-unavco-course/blob/main/README.md#license) states CC BY 4.0. @PaulWessel, which is correct so that I use the correct information in the new repository mentioned in [this forum post](https://forum.generic-mapping-tools.org/t/proposal-creating-a-separate-gmt-tutorial-page/2831/11?u=meghanj)?

**Comment by PaulWessel** [comment]
We have always done LGPL for GMT so I assume the CC only refers to the content of the README flle.  We are not doing a switch on the licensing for GMT I think at this point.

**Comment by maxrjones** [comment]
OK, closing this and will use LGPL for https://github.com/GenericMappingTools/gmt-for-geodesy
