### ISSUE TITLE
HW1

### ISSUE THREAD

**Issue by krkrueger** [GenericMappingTools/2021-unavco-course#3]
Working on the first homework. I am on RHEL, test_1 opens and works well. When I go to run test 2. It has an error for the webm but the mp4 creates okay.

>>bash test_2.sh
ERROR:
Unknown encoder 'libvpx'
movie [ERROR]: Running FFmpeg conversion to webM returned error 256 - exiting.

When I try to open count.mp4 I am missing a codec for gstreamer, which looking again looks like it requires superuser rights to update, anyway around this?

ERROR:
>>xdg-open count.mp4

** Message: Error: Your GStreamer installation is missing a plug-in.
gstdecodebin2.c(2943): gst_decode_bin_expose (): /GstPlayBin2:play/GstURIDecodeBin:uridecodebin0/GstDecodeBin2:decodebin20:
no suitable plugins found

** Message: Missing plugin: gstreamer|0.10|totem|H.264 decoder|decoder-video/x-h264, profile=(string)high, level=(string)1.2 (H.264 decoder)
** Message: PackageKit: xid = 113246212
** Message: PackageKit: Codec nice name: H.264 decoder
** Message: PackageKit: ignoring field named profile
** Message: PackageKit: ignoring field named level
** Message: PackageKit: structure: gstreamer0.10(decoder-video/x-h264)()(64bit)
** Message: PackageKit: Did not install codec: The name org.freedesktop.PackageKit was not provided by any .service files
** Message: No installation candidate for missing plugins found.
** Message: Error: Your GStreamer installation is missing a plug-in.
gstdecodebin2.c(2943): gst_decode_bin_expose (): /GstPlayBin2:play/GstURIDecodeBin:uridecodebin1/GstDecodeBin2:decodebin21:
no suitable plugins found

** Message: Missing plugin: gstreamer|0.10|totem|H.264 decoder|decoder-video/x-h264, profile=(string)high, level=(string)1.2 (ignoring)
** Message: All missing plugins are blacklisted, doing nothing

**Comment by PaulWessel** [comment]
Yes, if you are on a computer that is managed by IT and you have no system access then you need to tell whoever is responsible to add the suitable plugins.  These are basic ones to handle h264 video - I am surprised that is not added by default.  You can also try to open it in your browser as these may come with the right codecs.

You could of course also copy the mp4 file to a Windows or Mac and see if it plays well there.

**Comment by deollamas** [comment]
Similar problem, no webm file created but the mp4 was created okay.

Unknown encoder 'libvpx'
movie [ERROR]: Running FFmpeg conversion to webM returned error 256 - exiting.

**Comment by PaulWessel** [comment]
I think it is more important you are able to create and view MP4 since that is pretty much a standard.  So not a problem as long as one of them work for you.
