### ISSUE TITLE
Error Test 1

### ISSUE THREAD

**Issue by agp-earth** [GenericMappingTools/2021-unavco-course#4]
Hello!

I downloaded the GMT application bundle on my mac without issue. Then I went to test it with test 1 and I received the following error:

dyld: lazy symbol binding failed: Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /Applications/GMT-6.2.0.app/Contents/Resources/bin/../lib/libcurl.4.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /Applications/GMT-6.2.0.app/Contents/Resources/bin/../lib/libcurl.4.dylib
  Expected in: /usr/lib/libSystem.B.dylib

./test_1.sh: line 1: 17422 Abort trap: 6           "${BUNDLE_RESOURCES}/bin/gmt" "$@"
coast [ERROR]: Must specify -R option

I am not exactly sure what this issue here is as I am new to using GMT. Any help would be much appreciated!!
Thank you!

**Comment by PaulWessel** [comment]
Are you running an older macOS version?  The Bundle was built on Big Sur and it may not be compatible if you go too far back in time.

**Comment by agp-earth** [comment]
I am using macOS Sierra version 10.12.6

**Comment by PaulWessel** [comment]
I think your options will be to either upgrade your OS, if possible, or else install from source, probably via conda.

**Comment by agp-earth** [comment]
Hi Paul! I updated my OS (to Big Sur) and everything is running smoothly (tests 1 and 2 both run)! Thanks so much for your help!
